# compliance.py
# -------------
# This file handles metadata tagging and PII redaction for our RAG app.
#
# Week 18: Compliance
#
# Why does this matter?
# Real-world AI apps handle sensitive data all the time — sometimes
# without realizing it. A user might type their email into a chat box.
# A retrieved document might contain a phone number. An error log might
# capture a social security number.
#
# Two tools protect against this:
#
#   1. Metadata tagging: Label data so downstream systems know how to
#      handle it. A "confidential" tag means: don't cache this, don't
#      log it, treat it carefully.
#
#   2. Redaction: Before data touches a log, an analytics pipeline, or
#      a debug message, scrub out patterns that look like PII (personally
#      identifiable information). If the data never enters the log, it
#      can never leak from it.
#
# This is called "defense in depth" — multiple overlapping safeguards,
# so that if one fails, the others still protect the user.

import re

# ============================================================
# SECTION 1: TAG SCHEMA
# ============================================================
# These are the allowed values for each metadata field.
# Using constants (instead of raw strings) prevents typos and makes
# it easy to see the full set of options in one place.

# How sensitive is this data?
SENSITIVITY_PUBLIC       = "public"        # Safe to log, cache, display anywhere
SENSITIVITY_INTERNAL     = "internal"      # OK within our system, not for external sharing
SENSITIVITY_CONFIDENTIAL = "confidential"  # Contains PII or private content — handle carefully
SENSITIVITY_RESTRICTED   = "restricted"    # Highly sensitive — never log, never cache

# What category of data is this?
DATA_TYPE_OPERATIONAL = "operational"  # Normal app data (tech docs, queries about Python, etc.)
DATA_TYPE_PII         = "pii"          # Personally identifiable information
DATA_TYPE_PHI         = "phi"          # Protected health information
DATA_TYPE_FINANCIAL   = "financial"    # Financial details (card numbers, account info)

# Where did this data come from?
SOURCE_USER_INPUT    = "user_input"    # Typed by the user in the chat box
SOURCE_DOCUMENT      = "document"      # Loaded from our knowledge base
SOURCE_MODEL_OUTPUT  = "model_output"  # Generated by Gemini
SOURCE_VECTOR_STORE  = "vector_store"  # Retrieved from ChromaDB


# ============================================================
# SECTION 2: METADATA TAGGING
# ============================================================

def tag_data(content, source, sensitivity=SENSITIVITY_PUBLIC, data_type=DATA_TYPE_OPERATIONAL):
    """
    Attach compliance metadata to a piece of data.

    This doesn't modify the content itself — it wraps it in a dictionary
    that carries the content plus tags describing how it should be handled.

    Args:
        content:     The raw string (a document, a query, a model answer, etc.)
        source:      Where this data came from (use SOURCE_* constants above).
        sensitivity: How sensitive this data is (use SENSITIVITY_* constants).
        data_type:   What category of data this is (use DATA_TYPE_* constants).

    Returns:
        A dictionary with the content and its metadata tags.

    Example:
        tag_data("What is Python?", SOURCE_USER_INPUT)
        → {
            "content": "What is Python?",
            "metadata": {
                "source": "user_input",
                "sensitivity": "public",
                "data_type": "operational",
                "contains_pii": False,
            }
          }
    """
    # Automatically upgrade sensitivity if we detect PII in the content.
    # Public and internal data both get upgraded to confidential when PII
    # is found — internal only means "stay within the system," but PII
    # requires stronger handling than that.
    pii_found = _contains_pii(content)
    if pii_found and sensitivity in {SENSITIVITY_PUBLIC, SENSITIVITY_INTERNAL}:
        sensitivity = SENSITIVITY_CONFIDENTIAL

    return {
        "content": content,
        "metadata": {
            "source": source,
            "sensitivity": sensitivity,
            "data_type": DATA_TYPE_PII if pii_found else data_type,
            "contains_pii": pii_found,
        },
    }


def tag_document(content):
    """
    Tag a document loaded from the knowledge base.
    Documents start as public/operational unless PII is detected.
    """
    return tag_data(content, source=SOURCE_DOCUMENT)


def tag_user_input(content):
    """
    Tag a query typed by the user.
    User input is treated as internal by default — it might contain PII.
    """
    return tag_data(content, source=SOURCE_USER_INPUT, sensitivity=SENSITIVITY_INTERNAL)


def tag_model_output(content):
    """
    Tag an answer generated by Gemini.
    Model output is internal — it might echo back PII from the user's query.
    """
    return tag_data(content, source=SOURCE_MODEL_OUTPUT, sensitivity=SENSITIVITY_INTERNAL)


def tag_retrieved_docs(documents):
    """
    Tag a list of documents returned from the vector store.

    Args:
        documents: A list of document strings from ChromaDB.

    Returns:
        A list of tagged document dictionaries.
    """
    return [
        tag_data(doc, source=SOURCE_VECTOR_STORE)
        for doc in documents
    ]


# ============================================================
# SECTION 3: PII DETECTION
# ============================================================

# Regex patterns for common PII formats.
# Each tuple is (label, compiled_pattern).
# We compile once at module load time for performance.
_PII_PATTERNS = [
    ("email",        re.compile(r"\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b")),
    ("phone_us",     re.compile(r"\b(?:\+1[\s\-]?)?\(?\d{3}\)?[\s\-]?\d{3}[\s\-]?\d{4}\b")),
    ("ssn",          re.compile(r"\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b")),
    ("credit_card",  re.compile(r"\b(?:\d{4}[\s\-]?){3}\d{4}\b")),
    ("ip_address",   re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")),
    ("date_of_birth",re.compile(r"\b(?:dob|date of birth)[:\s]+\d{1,2}[/\-]\d{1,2}[/\-]\d{2,4}\b", re.IGNORECASE)),
]


def _contains_pii(text):
    """
    Return True if the text appears to contain any PII pattern.
    Used internally by tag_data() to auto-upgrade sensitivity.
    """
    if not text:
        return False
    for _label, pattern in _PII_PATTERNS:
        if pattern.search(text):
            return True
    return False


# ============================================================
# SECTION 4: REDACTION
# ============================================================

def redact_pii(text):
    """
    Replace PII patterns in text with safe placeholder tokens.

    This preserves the structure of the text (so it's still readable
    and useful for debugging) while removing the actual sensitive values.

    Args:
        text: Any string that might contain PII.

    Returns:
        The same string with PII replaced by [REDACTED_<TYPE>] tokens.

    Example:
        redact_pii("Contact me at john@example.com or 555-867-5309")
        → "Contact me at [REDACTED_EMAIL] or [REDACTED_PHONE_US]"
    """
    if not text:
        return text

    redacted = text
    for label, pattern in _PII_PATTERNS:
        placeholder = f"[REDACTED_{label.upper()}]"
        redacted = pattern.sub(placeholder, redacted)

    return redacted


def safe_log(label, content, force_redact=False):
    """
    Print a labeled log line with PII automatically redacted.

    Use this everywhere you'd normally write print() for debugging.
    It ensures that even in development, sensitive data doesn't appear
    in terminal output or log files.

    Args:
        label:        A short description of what's being logged.
        content:      The string to log.
        force_redact: If True, always redact even if no PII detected.
                      Useful for user input, which should always be treated carefully.

    Example:
        safe_log("user query", "My email is foo@bar.com")
        → [LOG] user query: My email is [REDACTED_EMAIL]
    """
    redacted = redact_pii(str(content)) if force_redact or _contains_pii(str(content)) else content
    print(f"[LOG] {label}: {redacted}")


def safe_error_log(label, error):
    """
    Log an error message with PII redacted from both the label and the error text.

    Args:
        label: Short description of where the error occurred.
        error: The exception or error string.
    """
    redacted_error = redact_pii(str(error))
    print(f"[ERROR] {label}: {redacted_error}")


def redact_for_model(tagged_item):
    """
    Optionally redact PII from a tagged item before sending it to Gemini.

    If the tagged item is marked as containing PII AND is confidential or
    restricted, we redact the content before it reaches the model. This
    prevents the model from echoing back or learning from sensitive values.

    Args:
        tagged_item: A dictionary returned by tag_data() or similar.

    Returns:
        The content string, redacted if appropriate.
    """
    metadata = tagged_item.get("metadata", {})
    content = tagged_item.get("content", "")

    sensitive_levels = {SENSITIVITY_CONFIDENTIAL, SENSITIVITY_RESTRICTED}
    if (
        metadata.get("contains_pii")
        and metadata.get("sensitivity") in sensitive_levels
    ):
        return redact_pii(content)

    return content


# ============================================================
# SECTION 5: UTILITY
# ============================================================

def get_sensitivity_level(tagged_item):
    """Return the sensitivity level string from a tagged item."""
    return tagged_item.get("metadata", {}).get("sensitivity", SENSITIVITY_PUBLIC)


def is_safe_to_log(tagged_item):
    """
    Return True if this item's sensitivity level allows logging.

    Public and internal data can be logged (after redaction).
    Confidential and restricted data should never be logged.
    """
    level = get_sensitivity_level(tagged_item)
    return level in {SENSITIVITY_PUBLIC, SENSITIVITY_INTERNAL}